export interface IConstants {
    OPUS_APPLICATION_VOIP: 1;
    OPUS_APPLICATION_AUDIO: 2;
    OPUS_APPLICATION_RESTRICTED_LOWDELAY: 3;
    OPUS_BANDWIDTH_NARROWBAND: 1;
    OPUS_BANDWIDTH_MEDIUMBAND: 2;
    OPUS_BANDWIDTH_WIDEBAND: 3;
    OPUS_BANDWIDTH_SUPERWIDEBAND: 4;
    OPUS_BANDWIDTH_FULLBAND: 5;
    OPUS_FRAMESIZE_ARG: 1;
    OPUS_FRAMESIZE_2_5_MS: 2;
    OPUS_FRAMESIZE_5_MS: 3;
    OPUS_FRAMESIZE_10_MS: 4;
    OPUS_FRAMESIZE_20_MS: 5;
    OPUS_FRAMESIZE_40_MS: 6;
    OPUS_FRAMESIZE_60_MS: 7;
    OPUS_FRAMESIZE_80_MS: 8;
    OPUS_FRAMESIZE_100_MS: 9;
    OPUS_FRAMESIZE_120_MS: 10;
}
